services:
  - type: web
    name: stock-market-dashboard
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff